# SPDX-FileCopyrightText: PyPSA-ASEAN, PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.7.0
foresight: myopic

run:
  name: asean-elec-v0 # use this to keep track of runs with different settings
  sector_name: asean-elec-v0
  shared_cutouts: true  # set to true to share the default cutout(s) across runs
                        # Note: value false requires build_cutout to be enabled

results_dir: results/
summary_dir: results/

scenario:
  clusters: [100]
  opts: "3h"
  planning_horizons: # investment years for myopic and perfect; or costs year for overnight
  - 2020
  - 2025
  - 2030
  - 2035
  - 2040
  - 2045
  - 2050
  sopts:
  - ""
  demand:
  - "DEC"

countries: [BN, KH, ID, LA, MM, MY, PH, SG, TH, TL, VN]

enable:
  retrieve_databundle: false #  Recommended 'true', for the first run. Otherwise data might be missing.
  retrieve_databundle_sector: true
  retrieve_cost_data: true # true: retrieves cost data from technology data and saves in resources/costs.csv, false: uses cost data in data/costs.csv
  download_osm_data: false # If 'true', OpenStreetMap data will be downloaded for the above given countries
  build_natura_raster: false # If True, then an exclusion raster will be build
  build_cutout: false

build_shape_options:
  simplify_gadm: false

subregion: # remove 'false' if subregion are to be specified
  enable:
    simplify_network: true
    cluster_network: true
  define_by_gadm:
    ID_Java-Bali: [ID.2_1, ID.4_1, ID.7_1, ID.9_1, ID.10_1, ID.11_1, ID.33_1]
    ID_Kalimantan: [ID.12_1, ID.13_1, ID.14_1, ID.34_1, ID.35_1]
    ID_Maluku: [ID.18_1, ID.19_1]
    ID_Nusa-Tenggara: [ID.20_1, ID.21_1]
    ID_Papua: [ID.22_1, ID.23_1]
    ID_Sulawesi: [ID.6_1, ID.25_1, ID.26_1, ID.27_1, ID.28_1, ID.29_1]
    ID_Sumatra: [ID.1_1, ID.3_1, ID.5_1, ID.8_1, ID.16_1, ID.17_1, ID.24_1, ID.30_1, ID.31_1, ID.32_1]
    MY_Peninsular: [MY.1_1, MY.2_1, MY.3_1, MY.4_1, MY.6_1, MY.7_1, MY.8_1, MY.9_1, MY.10_1, MY.11_1, MY.12_1, MY.15_1, MY.16_1]
    MY_Sabah: [MY.5_1, MY.13_1]
    MY_Sarawak: [MY.14_1]
    PH_Luzon: [PH.1_1, PH.5_1, PH.7_1, PH.8_1, PH.10_1, PH.11_1, PH.12_1, PH.13_1, PH.17_1, PH.18_1, PH.19_1, PH.20_1, PH.23_1, PH.24_1, PH.33_1, PH.34_1, PH.35_1, PH.37_1, H.38_1, PH.39_1, PH.40_1, PH.45_1, PH.46_1, PH.47_1, PH.50_1, PH.55_1, PH.56_1, PH.57_1, PH.58_1, PH.59_1, PH.60_1, PH.61_1, PH.62_1, PH.63_1, PH.64_1, PH.65_1, PH.69_1, PH.76_1, PH.78_1]
    PH_Visayas: [PH.4_1, PH.6_1, PH.14_1, PH.15_1, PH.22_1, PH.25_1, PH.31_1, PH.32_1, PH.36_1, PH.43_1, PH.51_1, PH.52_1, PH.54_1, PH.66_1, PH.68_1, PH.71_1]
    PH_Mindanao: [PH.2_1, PH.3_1, PH.9_1, PH.16_1, PH.21_1, PH.26_1, PH.27_1, PH.28_1, PH.29_1, PH.30_1, PH.41_1, PH.42_1, PH.44_1, PH.48_1, PH.49_1, PH.53_1, PH.67_1, PH.70_1, PH.72_1, PH.73_1, PH.74_1, PH.75_1, PH.77_1, PH.79_1, PH.80_1, PH.81_1]

focus_weights:
  BN: 0.0
  KH: 0.046396
  LA: 0.058770
  MM: 0.169951
  SG: 0.0
  TH: 0.131035
  TL: 0.0
  VN: 0.084013
  ID_Java-Bali: 0.035281
  ID_Kalimantan: 0.135732
  ID_Maluku: 0.0
  ID_Nusa-Tenggara: 0.016782
  ID_Papua: 0.0
  ID_Sulawesi: 0.046963
  ID_Sumatra: 0.120713    
  MY_Peninsular: 0.033556
  MY_Sarawak: 0.031638
  MY_Sabah: 0.018709
  PH_Luzon: 0.023487
  PH_Visayas: 0.023487
  PH_Mindanao: 0.023487

co2_budget:
  enable: true
  overwrite: true
  compare: 935.82e+06 # 929.5 MtCO₂-eq/year CO2 emission model results for 2020 (electricity only)
  year:
    2020: 1.0
    2025: 0.833
    2030: 0.667
    2035: 0.500
    2040: 0.333
    2045: 0.167
    2050: 0.0

electricity:
  base_network: osm-plus-prebuilt
  base_network_version: 0.1.1

transmission_projects:
  enable: true
  include:
    ID_SuperGrid: true
    AIMS: true
  skip: []
  status:
  - in_planning
  - under_construction
  - existing
  - under_consideration
  new_link_capacity: zero #keep or zero
  set_by_build_year: true

cluster_options:
  simplify_network:
    remove_stubs_across_borders: false
    p_threshold_drop_isolated: 50 # [MW] isolated buses are being discarded if bus mean power is below the specified threshold

costs:
  append_cost_data: true
  regional_factor: true

sector:
  enable:
    heat: false
    biomass: false
    industry: false
    shipping: false
    aviation: false
    land_transport: false
    rail_transport: false
    agriculture: false
    residential: false
    services: false

  hydrogen:
    network: false

  co2_network: false
  co2_sequestration_potential: 300 #MtCO2/a sequestration potential for ASEAN (https://onepetro.org/OTCONF/proceedings-abstract/22OTC/22OTC/D021S025R007/484411)

  land_transport_fuel_cell_share:
    DEC_2020: 0.00
    DEC_2025: 0.00
    DEC_2030: 0.00
    DEC_2035: 0.00
    DEC_2040: 0.00
    DEC_2045: 0.00
    DEC_2050: 0.00
  land_transport_electric_share:
    DEC_2020: 0.00
    DEC_2025: 0.00
    DEC_2030: 0.00
    DEC_2035: 0.00
    DEC_2040: 0.00
    DEC_2045: 0.00
    DEC_2050: 0.00
  shipping_hydrogen_share:
    DEC_2020: 0.00
    DEC_2025: 0.00
    DEC_2030: 0.00
    DEC_2035: 0.00
    DEC_2040: 0.00
    DEC_2045: 0.00
    DEC_2050: 0.00

export:
  enable: false
  h2export: [0]

solving:
  options:
    load_shedding: false