# SPDX-FileCopyrightText:  PyPSA-ASEAN, PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# ==== Baseline Scenarios ====
# ============================

baseline-aims-3H:

baseline-asean-3H:
  transmission_projects:
    include:
      AIMS: false

baseline-existing-3H:
  transmission_projects:
    include:
      AIMS: false
      ID_SuperGrid: false

# ==== Decarbonization Scenarios ====
# ===================================

decarbonize-aims-3H:
  co2_budget:
    enable: true

decarbonize-asean-3H:
  co2_budget:
    enable: true

  transmission_projects:
    include:
      AIMS: false

decarbonize-existing-3H:
  co2_budget:
    enable: true

  transmission_projects:
    include:
      AIMS: false
      ID_SuperGrid: false

# ====== Sensitivity Scenarios ======
# ===================================

sensitivity-overnight-3H:
  scenario:
    planning_horizons:
    - 2050

  co2_budget:
    enable: true

# ====== Clustering ======

sensitivity-50n-3H:
  scenario:
    clusters: 50
    planning_horizons:
    - 2050

  co2_budget:
    enable: true

sensitivity-200n-3H:
  scenario:
    clusters: 200
    planning_horizons:
    - 2050

  co2_budget:
    enable: true

# ====== Timesteps ======

sensitivity-1H:
  scenario:
    sopts:
    - "1h"
    planning_horizons:
    - 2050

  co2_budget:
    enable: true

sensitivity-6H:
  scenario:
    sopts:
    - "6h"
    planning_horizons:
    - 2050

  co2_budget:
    enable: true

# ====== Limit Rooftops ======

sensitivity-roof100-3H:
  scenario:
    planning_horizons:
    - 2050

  co2_budget:
    enable: true

  sector:
    solar_rooftop:
      install_ratio:
        0: 0
        10: 0
        100: 0.36
        200: 0.41
        450: 0.49
        2300: 0.66

sensitivity-roof200-3H:
  scenario:
    planning_horizons:
    - 2050

  co2_budget:
    enable: true

  sector:
    solar_rooftop:
      install_ratio:
        0: 0
        10: 0
        100: 0
        200: 0.41
        450: 0.49
        2300: 0.66

# ==== Tutorial Scenarios ====
# ============================

baseline-aims-3H-tutorial:
  tutorial: true

  scenario:
    clusters: [50]
    planning_horizons:
    - 2030
    - 2040
    - 2050

  snapshots:
    start: "2013-03-01"
    end: "2013-03-07"

  atlite:
    default: asean-2013-era5-tutorial

  sector:
    enable:
      land_transport: false # Ongoing issues for models with short timeframes

    solar_rooftop:
      use_building_size: false

  solving:
    solver:
      name: highs
      options: highs-default

baseline-java-bali-3H-tutorial:
  tutorial: true

  scenario:
    clusters: [50]
    planning_horizons:
    - 2030
    - 2040
    - 2050

  snapshots:
    start: "2013-03-01"
    end: "2013-03-07"

  countries: [ID]

  focus_weights:
    ID_Java-Bali: 0.7 # Focus resolution on Java-Bali
    ID_Kalimantan: 0.1
    ID_Maluku: 0.0
    ID_Nusa-Tenggara: 0.05
    ID_Papua: 0.0
    ID_Sulawesi: 0.0
    ID_Sumatra: 0.15

  atlite:
    default: asean-2013-era5-tutorial

  sector:
    enable:
      land_transport: false # Ongoing issues for models with short timeframes

    solar_rooftop:
      use_building_size: false

  final_adjustment:
    drop_country: [ID_Maluku, ID_Papua, ID_Sulawesi]

  solving:
    solver:
      name: highs
      options: highs-default

baseline-peninsular-3H-tutorial:
  tutorial: true

  scenario:
    clusters: [50]
    planning_horizons:
    - 2030
    - 2040
    - 2050

  snapshots:
    start: "2013-03-01"
    end: "2013-03-07"

  countries: [ID, MY, SG, TH]

  focus_weights:
    ID: 0.0
    MY: 0.0
    TH: 0.15
    SG: 0.0
    ID_Sumatra: 0.15
    MY_Peninsular: 0.7

  subregion:
    method: gadm
    apply_on: ["simplify_network", "cluster_network", "final_adjustment"]
    define_by_gadm:
      ID_Java-Bali: []
      ID_Kalimantan: []
      ID_Maluku: []
      ID_Nusa-Tenggara: []
      ID_Papua: []
      ID_Sulawesi: []
      ID_Sumatra: [ID.1_1, ID.3_1, ID.5_1, ID.8_1, ID.16_1, ID.17_1, ID.24_1, ID.30_1, ID.31_1, ID.32_1]
      MY_Peninsular: [MY.1_1, MY.2_1, MY.3_1, MY.4_1, MY.6_1, MY.7_1, MY.8_1, MY.9_1, MY.10_1, MY.11_1, MY.12_1, MY.15_1, MY.16_1]
      MY_Sabah: []
      MY_Sarawak: []

  atlite:
    default: asean-2013-era5-tutorial

  sector:
    enable:
      land_transport: false # Ongoing issues for models with short timeframes

    solar_rooftop:
      use_building_size: false

  final_adjustment:
    drop_country: [MY, ID]
