# SPDX-FileCopyrightText: PyPSA-ASEAN, PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

# ==== Baseline Scenarios ====
# ============================

baseline-aims-3H:

baseline-asean-3H:
  transmission_projects:
    include:
      AIMS: false

baseline-existing-3H:
  transmission_projects:
    include:
      AIMS: false
      ID_SuperGrid: false

# ==== Decarbonization Scenarios ====
# ===================================

decarbonize-aims-3H:
  co2_budget:
    enable: true

decarbonize-asean-3H:
  co2_budget:
    enable: true

  transmission_projects:
    include:
      AIMS: false

decarbonize-existing-3H:
  co2_budget:
    enable: true

  transmission_projects:
    include:
      AIMS: false
      ID_SuperGrid: false